name: shogun
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3
  - Click
  - pyyaml
  - pandas
  - scipy
  - numpy
  - cytoolz
  - pip
  - pip:
    - "git+https://github.com/knights-lab/SHOGUN.git"
